name: Next.js CI

on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: diet-app

    steps:
      - uses: actions/checkout@v4

      - name: Show tree
        run: |
          pwd
          ls -la
          test -f package.json || (echo "package.json not found in $(pwd)"; exit 1)
          test -f ../diet-app/package-lock.json || (echo "diet-app/package-lock.json missing at repo root path"; exit 1)

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: diet-app/package-lock.json

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Test
        run: npm test --if-present

      - name: Build
        run: npm run build
